# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: TTM
    ports:
      - 3307:3306
    volumes:
      - ../../../db/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

